# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-02 12:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('fprogramdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('euodp_url', models.URLField()),
                ('file_url', models.URLField()),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='merged_ids',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
